name: veteranscope
favicon: null
layout_spectrum: 0.36033
typography_spectrum: 0.8381708378437907
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#141510'
    - '#b2373c'
    - '#6d6226'
    - '#9d8757'
  brandStrength: 0.334822217002511
  lightness: 0.8251362724695355
  saturation: 0.26312720007263124
  rhythmicContrast: 0.32674332545138896
purpose: []
