name: veteranscope
favicon: null
layout_spectrum: 0.5467
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000d28'
    - '#6a0f16'
    - '#b1c3c3'
    - '#778993'
    - '#d63d40'
  brandStrength: 0.334822217002511
  lightness: 0.4375
  saturation: 0.8125
  rhythmicContrast: 0.32674332545138896
purpose: []
